# site settings
title: Guzman Vigliecca
#subtitle: by HTML5 UP
email: mpzokrnz
description: Software Engineer | MSc in Computer Science | Fulbright Scholar
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Canelones 1588
city: Montevideo
#zip_code: 02135
country: Uruguay
phone: +598 92454005

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/guzmanvig
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/guzman-vigliecca
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
